"""improve comments model

Revision ID: 0f825dd4062f
Revises: 8111449dca7e
Create Date: 2026-07-11 18:47:51.982952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f825dd4062f'
down_revision: Union[str, Sequence[str], None] = '8111449dca7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.alter_column('comments', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comments', 'parent_comment_id')
    # ### end Alembic commands ###
