"""add  columns to users table

Revision ID: 65919e277d32
Revises: c9191aa601b1
Create Date: 2026-07-25 12:15:19.073290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65919e277d32'
down_revision: Union[str, Sequence[str], None] = 'c9191aa601b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "users",
        sa.Column("profile_picture", sa.String(), nullable=True)
    )

    op.add_column(
        "users",
        sa.Column("profile_picture_mime", sa.String(), nullable=True)
    )

    op.add_column(
        "users",
        sa.Column("profile_picture_size", sa.BigInteger(), nullable=True)
    )
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_picture_size")
    op.drop_column("users", "profile_picture_mime")
    op.drop_column("users", "profile_picture")
    # ### end Alembic commands ###
