"""improve follow model

Revision ID: 8111449dca7e
Revises: 76b77002222f
Create Date: 2026-07-10 08:31:13.533634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8111449dca7e'
down_revision: Union[str, Sequence[str], None] = '76b77002222f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('following_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_follower_following', 'followers', ['follower_id', 'following_id'])
    op.drop_constraint(op.f('followers_followed_id_fkey'), 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'users', ['following_id'], ['id'], ondelete='CASCADE')
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(op.f('followers_followed_id_fkey'), 'followers', 'users', ['followed_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_follower_following', 'followers', type_='unique')
    op.drop_column('followers', 'following_id')
    # ### end Alembic commands ###
