"""update Livestreams models

Revision ID: cf8276882bd7
Revises: 7fee1c425dd6
Create Date: 2026-07-29 18:29:22.405131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8276882bd7'
down_revision: Union[str, Sequence[str], None] = '7fee1c425dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_streams', sa.Column('description', sa.String(), nullable=True))
    op.add_column('live_streams', sa.Column('category', sa.String(), nullable=True))
    op.add_column('live_streams', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('live_streams', sa.Column('playback_url', sa.String(), nullable=True))
    op.add_column('live_streams', sa.Column('current_viewers', sa.Integer(), nullable=True))
    op.add_column('live_streams', sa.Column('peak_viewers', sa.Integer(), nullable=True))
    op.add_column('live_streams', sa.Column('recording_url', sa.String(), nullable=True))
    op.alter_column('live_streams', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('live_streams', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('live_streams', 'stream_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('live_streams', 'stream_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('live_streams', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('live_streams', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('live_streams', 'recording_url')
    op.drop_column('live_streams', 'peak_viewers')
    op.drop_column('live_streams', 'current_viewers')
    op.drop_column('live_streams', 'playback_url')
    op.drop_column('live_streams', 'thumbnail')
    op.drop_column('live_streams', 'category')
    op.drop_column('live_streams', 'description')
    # ### end Alembic commands ###
