worker_processes auto;

events {
    worker_connections 1024;
}

########################################
# RTMP SERVER
########################################

rtmp {

    server {

        # RTMP listens on port 1935
        listen 1935;

        # Size of each RTMP packet
        chunk_size 4096;

      application live {

    live on;

    record off;

    # ---------------------------------
    # HLS
    # ---------------------------------

    hls on;

    hls_path /var/www/hls;

    hls_fragment 2s;

    hls_playlist_length 10s;

    # ---------------------------------
    # FastAPI callbacks
    # ---------------------------------

    on_publish http://127.0.0.1:8000/livestreams/on_publish;

    on_done http://127.0.0.1:8000/livestreams/on_done;
}
    }
}

########################################
# HTTP SERVER
########################################

http {

    include       mime.types;

    default_type  application/octet-stream;

    sendfile on;

    tcp_nopush on;

    keepalive_timeout 65;

    ####################################
    # Load all reverse proxy configs
    ####################################

    include /etc/nginx/conf.d/*.conf;
}